[package]
name = "python-lctree"
version = "0.3.4"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "lctree_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.27.0"
lctree = { path = ".." }
